# spring:
#   datasource:
#     url: jdbc:sqlserver://mitch-todo-sql.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#     username: mitch@hawkins5.com
#     password:
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#       dialect: org.hibernate.dialect.SQLServer2012Dialect

# server:
#   port: 9191
